import type { Property } from "@/types";

export const PROPERTIES: Property[] = [
  {
    id: "1",
    slug: "skyline-penthouse",
    title: "Skyline Penthouse",
    location: "Manhattan, New York",
    price: 12500000,
    currency: "USD",
    bedrooms: 4,
    bathrooms: 5,
    area: 4800,
    status: "for-sale",
    featured: true,
    image: "/images/property-1.svg",
    description:
      "An extraordinary penthouse perched above the Manhattan skyline, featuring floor-to-ceiling windows, a private rooftop terrace, and bespoke Italian finishes throughout.",
    amenities: ["Rooftop Terrace", "Wine Cellar", "Smart Home", "Concierge", "Private Elevator"],
  },
  {
    id: "2",
    slug: "coastal-villa",
    title: "Coastal Villa",
    location: "Malibu, California",
    price: 8900000,
    currency: "USD",
    bedrooms: 5,
    bathrooms: 6,
    area: 6200,
    status: "for-sale",
    featured: true,
    image: "/images/property-2.svg",
    description:
      "A stunning oceanfront villa with panoramic Pacific views, infinity pool, and direct beach access. Designed for seamless indoor-outdoor living.",
    amenities: ["Infinity Pool", "Beach Access", "Home Theater", "Guest House", "Ocean Views"],
  },
  {
    id: "3",
    slug: "modern-townhouse",
    title: "Modern Townhouse",
    location: "Chelsea, London",
    price: 4200000,
    currency: "GBP",
    bedrooms: 4,
    bathrooms: 3,
    area: 3100,
    status: "for-sale",
    featured: true,
    image: "/images/property-3.svg",
    description:
      "A meticulously restored Georgian townhouse blending period charm with contemporary luxury. Private garden and chef's kitchen included.",
    amenities: ["Private Garden", "Chef's Kitchen", "Study", "Period Features", "Garage"],
  },
  {
    id: "4",
    slug: "lakeside-estate",
    title: "Lakeside Estate",
    location: "Lake Como, Italy",
    price: 15700000,
    currency: "EUR",
    bedrooms: 7,
    bathrooms: 8,
    area: 9800,
    status: "for-sale",
    featured: false,
    image: "/images/property-4.svg",
    description:
      "A magnificent lakeside estate with private dock, manicured gardens, and breathtaking views of the Italian Alps reflected in crystal-clear waters.",
    amenities: ["Private Dock", "Helipad", "Spa", "Vineyard", "Staff Quarters"],
  },
  {
    id: "5",
    slug: "urban-loft",
    title: "Urban Loft",
    location: "SoHo, New York",
    price: 3200000,
    currency: "USD",
    bedrooms: 2,
    bathrooms: 2,
    area: 2200,
    status: "for-rent",
    featured: false,
    image: "/images/property-5.svg",
    description:
      "A converted warehouse loft with soaring ceilings, exposed brick, and an open-plan layout perfect for the modern creative professional.",
    amenities: ["High Ceilings", "Exposed Brick", "Rooftop Access", "Gym", "Doorman"],
  },
  {
    id: "6",
    slug: "desert-retreat",
    title: "Desert Retreat",
    location: "Scottsdale, Arizona",
    price: 5800000,
    currency: "USD",
    bedrooms: 4,
    bathrooms: 4,
    area: 4500,
    status: "for-sale",
    featured: false,
    image: "/images/property-6.svg",
    description:
      "An architectural masterpiece set against the Sonoran Desert, featuring rammed earth walls, a resort-style pool, and uninterrupted mountain vistas.",
    amenities: ["Resort Pool", "Mountain Views", "Outdoor Kitchen", "Fire Pit", "Solar Panels"],
  },
];

export const FEATURED_PROPERTIES = PROPERTIES.filter((p) => p.featured);
